### ISSUE TITLE
Support for Python 3.11

### ISSUE THREAD

**Issue by oalfred** [Reddan/checkpointer#1]
Hi!

We just discovered that checkpointer does not work with Python 3.11, it fails in `utils.py` with this error

```python
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
```

If you want to continue to maintain this we'd be more than happy, we are still using it daily, otherwise we'll look around for alternatives.

**Comment by Reddan** [comment]
Took a while but now it's fixed!

**Comment by oalfred** [comment]
Thanks! 👍
